[package]
name = "cargo-nono"
version = "0.1.0"
authors = ["Maximilian Goisser <goisser94@gmail.com>"]
description = "Detect (possible) no_std compatibility of your crate and dependencies"
keywords = ["cargo", "no_std", "nono", "subcommand"]
license = "MIT OR Apache-2.0"

[dependencies]
cargo_metadata = "0.6.1"
serde = "1.0.80"
serde_json = "1.0.33"
console = "0.6.2"
syn = { version = "=0.15.18", default-features = false, features = ["full", "extra-traits", "parsing"] }
quote = "0.6.10"
clap = "2.32.0"
